IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " flir-capture"
IMAGE_INSTALL_append = " v4l2-capture"
IMAGE_INSTALL_append = " trd-files"
IMAGE_INSTALL_append = " trd-files-dev"
IMAGE_INSTALL_append = " packagegroup-trd"
IMAGE_INSTALL_append = " packagegroup-trd-dev"
